{{- if .Values.secret.enabled -}}
{{- if .Values.secret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
type: Opaque
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anything-llm.fullname" . }}-secret
  namespace: {{ .Release.Name }}
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end -}}
{{- end -}}
