apiVersion: v1
kind: Service
metadata:
  name: {{ include "anything-llm.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "anything-llm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
